name: Deploy Supabase Function

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/send-contact-email/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -sL https://install.supabase.com/linux | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Deploy Edge Function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref dbmvtqvualzpqpjsqdwq
          supabase functions deploy send-contact-email --no-verify-jwt
